apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/turnkey-chimera-222516/pipeline:f10c42af071b37a50a305776a7698d3def5079a5
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
